### ISSUE TITLE
Has lineage.openhumans.org been hacked?

### ISSUE THREAD

**Issue by jcnventura** [apriha/lineage_app#6]
I was trying to find out more about this tool, and went to lineage.openhumans.org, but ended up being redirected to orders.sensualkinfactory.com

**Comment by apriha** [comment]
Please see https://www.openhumans.org/activity/lineage/ . Open Humans Foundation has managed the Open Humans lineage project since December 3 2019, so I'd recommend reaching out to Open Humans. Thanks.
